  import Head from 'next/head'
  import Layout from '@/components/Layout'
  import Image from 'next/image'
  import profilePic from "../../public/images/profile/developertest.png"
  import AnimatedText from '@/components/AnimatedText'
  import Link from 'next/link'
  import { LinkArrow } from '@/components/Icons'
  import Hireme from '@/components/Hireme'
  import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"


  export default function Home() {
    return (
      <>
        <Head>
          <title>New Portfolio</title>
          <meta name="description" content="Generated by create next app" /> 
        </Head>
        <main className='pt-0 flex items-center text-dark w-full min-h-screen dark:text-light'> 
          <Layout className='pt-0 md:pt-16 sm:pt-8'>
            <div className='flex items-center justify-between w-full lg:flex-col'>
              <div className='w-1/2 md:w-full'>
                <Image src={profilePic} alt='Techates' className='w-full h-auto 
                lg:hidden md:inline-block md:w-full '
                priority
                sizes='(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                33vw'/>
              </div>
              <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
                <AnimatedText text={'Crafting compelling web experiences - design, development, and digital marketing that captivates.'} 
                className='!text-6xl !text-left xl:text-5xl lg:!text-center lg:!text-4xl md:!text-3xl sm:!text-2xl'/>
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                  We bring your brand to life online. From web development and UI/UX design to captivating photography, videography, and strategic digital marketing,
                  we craft immersive user experiences that elevate your brand.
                </p>
                <div className='flex items-center self-start mt-2 lg:self-center'>
                  <Link href="/Vision and Mission.pdf" target='_blank' className='flex items-left bg-dark text-light p-2 px-2.5 rounded-lg text-lg font-semibold hover:bg-light
                   hover:text-dark border-2 border-solid border-transparent hover:border-dark
                   dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                   md:p-2 md:px-4 md:text-base'>
                    Vision! <LinkArrow className='w-6 ml-1' />
                  </Link>
                  <Link href="mailto:techateshq@gmail.com" target='_blank' className='ml-4 text-lg font-medium capitalize 
                  text-dark underline dark:text-light md:text-base'>
                    Contact
                  </Link>
                </div>
              </div>
            </div>
          </Layout>
          <Hireme />
          <div className='absolute right-8 bottom-1 inline-block w-12 md:hidden'>
            <Image src={lightBulb} alt='Techates' className='w-auto h-full'/>
          </div>
        </main>
      </>
    )
  }
